### ISSUE TITLE
Contacts' profile pictures are too small.

### ISSUE THREAD

**Issue by stefanmaric** [telegram-s/telegram#57]
The contacts' profile pictures are showing in a very low resolution.

It's probably loading the thumbnail instead of the appropriate picture.

**Comment by stefanmaric** [comment]
I'll close this issue since it only appears on the the Beta version from the Play Store. Why the Beta version is behind the 'stable' one?

**Comment by stefanmaric** [comment]
Reopen, I took a closer look and it does show pictures in low resolution.

Here a comparison between the Telegram N (first one) and Telegram S (and S beta):

![index](https://cloud.githubusercontent.com/assets/1009040/2643937/201847be-bf22-11e3-96d6-3adf814a971d.jpeg)

![index2](https://cloud.githubusercontent.com/assets/1009040/2643941/251d89fe-bf22-11e3-9d88-81b4799b4b17.jpeg)

**Comment by Ecron** [comment]
My question is: Why do you want a good quality picture if you can't save it to your gallery?

In Telegram Official you actually can do it, so it's normal that it loads in good quality, but in Telegram S... I don't see the point.

**Comment by stefanmaric** [comment]
It's not to save it, it simply isn't good enough to ~~stalk~~ appreciate the profile pictures. :D

Maybe another example would point it better:

Telegram N:

![screenshot_2014-05-20-15-13-57](https://cloud.githubusercontent.com/assets/1009040/3032436/c75a35e0-e057-11e3-8b32-85840bf650e0.png)

That was ok, I can even read the t-shirt... Now telegram S:

![screenshot_2014-05-20-15-14-03](https://cloud.githubusercontent.com/assets/1009040/3032442/d33bfa9c-e057-11e3-90d4-636492c1e449.png)

Not that ok. See? :)

**Comment by Ecron** [comment]
Well, those screenshots you attach are zoomed, I asume, because if not the picture would be in a squared shape... So, when you don't zoom the profile picture, it shows pretty well, but when you zoom it in, it looks blurred... 

I agree with you when you say that pictures would have good quality, everybody like to see pictures well, but, if you think in the practical use of it, lowing a bit the quality improves the loading time and as you can't save it to your phone, the problem doesn't seem too big.

If you try Telegram N (or Telegram Official), you'd see it happens the same BUT with pictures sent in the chat. THAT'S a problem, because when you save the picture to  your gallery, it's in a low shameful quality.

Anyway, I see your point, quality would be a bit higher (not full quality, but a decent one at least) :wink:
